import type { Event, Category, Group } from "./types"

// Updated categories
export const categories: Category[] = [
  { id: "clubs", name: "Clubs" },
  { id: "workshops", name: "Workshops" },
  { id: "asivc", name: "ASIVC" },
  { id: "academic", name: "Academic" },
  { id: "cultural", name: "Cultural" },
  { id: "sports", name: "Sports" },
  { id: "career", name: "Career" },
  { id: "other", name: "Other" },
]

// Groups data (renamed from organizations)
export const groups: Group[] = [
  {
    id: "group1",
    name: "Academic Success Center",
    description: "Providing resources and support to help students achieve academic excellence.",
    categoryId: "academic",
    categoryName: "Academic",
    contactEmail: "success@ivc.edu",
  },
  {
    id: "group2",
    name: "Asian Student Association",
    description: "Promoting Asian culture and providing a supportive community for Asian students.",
    categoryId: "clubs",
    categoryName: "Clubs",
    contactEmail: "asa@ivc.edu",
  },
  {
    id: "group3",
    name: "Athletics Department",
    description: "Organizing sports events and promoting physical fitness on campus.",
    categoryId: "sports",
    categoryName: "Sports",
    contactEmail: "athletics@ivc.edu",
  },
  {
    id: "group4",
    name: "Photography Club",
    description: "A community for photography enthusiasts to share their work and learn new techniques.",
    categoryId: "clubs",
    categoryName: "Clubs",
    contactEmail: "photo@ivc.edu",
  },
  {
    id: "group5",
    name: "Career Services",
    description: "Helping students prepare for their careers through workshops, job fairs, and one-on-one counseling.",
    categoryId: "career",
    categoryName: "Career",
    contactEmail: "careers@ivc.edu",
  },
  {
    id: "group6",
    name: "Office of Diversity and Inclusion",
    description: "Promoting diversity, equity, and inclusion on campus through education and advocacy.",
    categoryId: "other",
    categoryName: "Other",
    contactEmail: "diversity@ivc.edu",
  },
  {
    id: "group7",
    name: "Music Department",
    description: "Offering music education and performance opportunities for students of all skill levels.",
    categoryId: "cultural",
    categoryName: "Cultural",
    contactEmail: "music@ivc.edu",
  },
  {
    id: "group8",
    name: "Computer Science Club",
    description: "A community for students interested in computer science and programming.",
    categoryId: "clubs",
    categoryName: "Clubs",
    contactEmail: "cs@ivc.edu",
  },
  {
    id: "group9",
    name: "Campus Recreation",
    description: "Organizing recreational activities and intramural sports for students.",
    categoryId: "sports",
    categoryName: "Sports",
    contactEmail: "recreation@ivc.edu",
  },
  {
    id: "group10",
    name: "Environmental Club",
    description: "Promoting environmental awareness and sustainability on campus and in the community.",
    categoryId: "clubs",
    categoryName: "Clubs",
    contactEmail: "environment@ivc.edu",
  },
  {
    id: "group11",
    name: "International Student Association",
    description: "Supporting international students and promoting cultural exchange.",
    categoryId: "cultural",
    categoryName: "Cultural",
    contactEmail: "international@ivc.edu",
  },
  {
    id: "group12",
    name: "ASIVC",
    description:
      "The Associated Students of Irvine Valley College, representing student interests in campus governance.",
    categoryId: "asivc",
    categoryName: "ASIVC",
    contactEmail: "asivc@ivc.edu",
  },
  {
    id: "group13",
    name: "Health Center",
    description: "Providing health services and education to students.",
    categoryId: "other",
    categoryName: "Other",
    contactEmail: "health@ivc.edu",
  },
]

// Updated events data with groupId
export const events: Event[] = [
  {
    id: "event1",
    title: "Final Exam Preparation Workshop",
    description:
      "Join us for a comprehensive workshop designed to help you prepare for your final exams. We'll cover effective study strategies, time management techniques, and provide resources to help you succeed.",
    startTime: "2025-04-10T14:00:00",
    endTime: "2025-04-10T16:00:00",
    location: "Library, Room 201",
    groupId: "group1",
    groupName: "Academic Success Center",
    categoryId: "workshops",
    categoryName: "Workshops",
    additionalInfo:
      "Please bring your laptop and any study materials you'd like to work with. Refreshments will be provided.",
  },
  {
    id: "event2",
    title: "Lunar New Year Celebration",
    description:
      "Celebrate the Lunar New Year with traditional performances, food, and activities. Learn about the cultural significance of this important holiday and join in the festivities.",
    startTime: "2025-04-05T18:00:00",
    endTime: "2025-04-05T21:00:00",
    location: "Student Center, Main Hall",
    groupId: "group2",
    groupName: "Asian Student Association",
    categoryId: "cultural",
    categoryName: "Cultural",
    additionalInfo:
      "Traditional attire is encouraged but not required. This event is open to all students, faculty, and community members.",
  },
  {
    id: "event3",
    title: "Basketball Tournament",
    description:
      "Participate in or cheer for your favorite team in our annual basketball tournament. Teams from various departments and student organizations will compete for the championship title.",
    startTime: "2025-04-12T09:00:00",
    endTime: "2025-04-12T17:00:00",
    location: "Hart Gymnasium",
    groupId: "group3",
    groupName: "Athletics Department",
    categoryId: "sports",
    categoryName: "Sports",
    additionalInfo: "Registration for teams closed on March 30. Spectators are welcome to attend free of charge.",
  },
  {
    id: "event4",
    title: "Photography Club Meeting",
    description:
      "Weekly meeting of the Photography Club. This week, we'll be discussing landscape photography techniques and reviewing members' recent work.",
    startTime: "2025-04-06T15:30:00",
    endTime: "2025-04-06T17:00:00",
    location: "Arts Building, Room A112",
    groupId: "group4",
    groupName: "Photography Club",
    categoryId: "clubs",
    categoryName: "Clubs",
    additionalInfo:
      "New members are always welcome! Bring your camera if you have one, but it's not required to participate.",
  },
  {
    id: "event5",
    title: "Career Fair",
    description:
      "Connect with over 50 employers from various industries who are looking to hire IVC students and alumni. Bring your resume and dress professionally.",
    startTime: "2025-04-15T10:00:00",
    endTime: "2025-04-15T15:00:00",
    location: "Student Center, Grand Ballroom",
    groupId: "group5",
    groupName: "Career Services",
    categoryId: "career",
    categoryName: "Career",
    additionalInfo:
      "Pre-registration is recommended but not required. Resume review services will be available on-site.",
  },
  {
    id: "event6",
    title: "Diversity and Inclusion Workshop",
    description:
      "An interactive workshop focused on promoting diversity, equity, and inclusion on campus. Learn about unconscious bias, cultural competence, and strategies for creating a more inclusive environment.",
    startTime: "2025-04-08T13:00:00",
    endTime: "2025-04-08T15:30:00",
    location: "Business Building, Room 305",
    groupId: "group6",
    groupName: "Office of Diversity and Inclusion",
    categoryId: "workshops",
    categoryName: "Workshops",
    additionalInfo: "This workshop counts toward professional development credits for faculty and staff.",
  },
  {
    id: "event7",
    title: "Spring Concert",
    description:
      "Join us for an evening of music featuring performances by the IVC Jazz Ensemble, Chamber Choir, and Symphony Orchestra. The program includes works by Mozart, Duke Ellington, and contemporary composers.",
    startTime: "2025-04-18T19:00:00",
    endTime: "2025-04-18T21:30:00",
    location: "Performing Arts Center",
    groupId: "group7",
    groupName: "Music Department",
    categoryId: "cultural",
    categoryName: "Cultural",
    additionalInfo: "Tickets are $10 for students, $15 for general admission. Available at the box office or online.",
  },
  {
    id: "event8",
    title: "Hackathon: Code for Good",
    description:
      "A 24-hour coding marathon where students collaborate to develop solutions for local non-profit organizations. All skill levels are welcome, from beginners to advanced programmers.",
    startTime: "2025-04-20T09:00:00",
    endTime: "2025-04-21T09:00:00",
    location: "Technology Building, Labs 101-105",
    groupId: "group8",
    groupName: "Computer Science Club",
    categoryId: "clubs",
    categoryName: "Clubs",
    additionalInfo:
      "Food and refreshments will be provided. Bring your laptop and any other equipment you might need. Teams of 3-5 people are recommended.",
  },
  {
    id: "event9",
    title: "Volleyball Tournament",
    description:
      "Intramural volleyball tournament open to all students. Form a team with your friends or sign up individually to be placed on a team.",
    startTime: "2025-04-14T16:00:00",
    endTime: "2025-04-14T20:00:00",
    location: "Hart Gymnasium",
    groupId: "group9",
    groupName: "Campus Recreation",
    categoryId: "sports",
    categoryName: "Sports",
    additionalInfo: "Registration deadline is April 10. Teams must have at least 6 players.",
  },
  {
    id: "event10",
    title: "Resume Building Workshop",
    description:
      "Learn how to create a standout resume that will catch employers' attention. This workshop covers formatting, content, and tailoring your resume for specific job applications.",
    startTime: "2025-04-07T11:00:00",
    endTime: "2025-04-07T12:30:00",
    location: "Career Center, Room 150",
    groupId: "group5",
    groupName: "Career Services",
    categoryId: "workshops",
    categoryName: "Workshops",
    additionalInfo:
      "Bring a draft of your current resume if you have one. Computers will be available for those who need them.",
  },
  {
    id: "event11",
    title: "Environmental Club Beach Cleanup",
    description:
      "Join the Environmental Club for our monthly beach cleanup event. Help keep our local beaches clean and learn about marine conservation efforts.",
    startTime: "2025-04-13T08:00:00",
    endTime: "2025-04-13T12:00:00",
    location: "Meet at Student Center for transportation",
    groupId: "group10",
    groupName: "Environmental Club",
    categoryId: "clubs",
    categoryName: "Clubs",
    additionalInfo:
      "Gloves, bags, and tools will be provided. Wear comfortable clothes and sunscreen. Community service hours will be awarded.",
  },
  {
    id: "event12",
    title: "International Food Festival",
    description:
      "Experience cuisines from around the world prepared by international student groups. Each booth will feature food, information about the country, and cultural displays.",
    startTime: "2025-04-16T11:30:00",
    endTime: "2025-04-16T14:00:00",
    location: "Campus Quad",
    groupId: "group11",
    groupName: "International Student Association",
    categoryId: "cultural",
    categoryName: "Cultural",
    additionalInfo:
      "Food tickets are $1 each, with most dishes costing 2-4 tickets. Proceeds support international student scholarships.",
  },
  {
    id: "event13",
    title: "ASIVC General Meeting",
    description:
      "Bi-weekly meeting of the Associated Students of Irvine Valley College. Learn about upcoming initiatives, budget allocations, and opportunities to get involved in student government.",
    startTime: "2025-04-09T15:00:00",
    endTime: "2025-04-09T16:30:00",
    location: "Student Services Building, Room 120",
    groupId: "group12",
    groupName: "ASIVC",
    categoryId: "asivc",
    categoryName: "ASIVC",
    additionalInfo: "All students are welcome to attend. Refreshments will be provided.",
  },
  {
    id: "event14",
    title: "ASIVC Student Leadership Conference",
    description:
      "A day-long conference focused on developing leadership skills, networking with campus leaders, and learning about opportunities in student government.",
    startTime: "2025-04-22T09:00:00",
    endTime: "2025-04-22T16:00:00",
    location: "Student Center, Conference Rooms A-C",
    groupId: "group12",
    groupName: "ASIVC",
    categoryId: "asivc",
    categoryName: "ASIVC",
    additionalInfo: "Registration required. Lunch and materials will be provided.",
  },
  {
    id: "event15",
    title: "Campus Blood Drive",
    description: "Donate blood to help save lives in our community. Each donation can save up to three lives.",
    startTime: "2025-04-17T10:00:00",
    endTime: "2025-04-17T15:00:00",
    location: "Student Center, Room 130",
    groupId: "group13",
    groupName: "Health Center",
    categoryId: "other",
    categoryName: "Other",
    additionalInfo: "Appointments recommended but walk-ins welcome. Please bring ID and eat before donating.",
  },
]

